/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  developerSidebar: [
    /// "projects/about",
    {
      type: "category",
      label: "afetharita",
      link: {type: "doc", id: "projects/afetharita.com/afetharita.com"},
      items: [
        {
          type: "autogenerated",
          dirName: "projects/afetharita.com",
        },
      ],
    },
    {
      type: "category",
      label: "deprem.io",
      items: [
        {
          type: "autogenerated",
          dirName: "projects/deprem.io",
        },
      ],
    },
  ],
};

module.exports = sidebars;