/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  productSidebar: [
    "product/product",
    {
      type: "category",
      label: "Vision and Mission",
      items: [
        {
          type: "autogenerated",
          dirName: "product/vision_mission",
        },
      ],
    },
    { type: "category", 
    label: "Onboarding", 
    items: [
      {
        type: "autogenerated",
        dirName: "product/onboarding",
      },
    ]
    },
    {
      type: "category",
      label: "Progress",
      items: [
        {
          type: "autogenerated",
          dirName: "product/progress",
        },
      ],
    },
    {
      type: "category",
      label: "Meetings",
      items: [
        {
          type: "autogenerated",
          dirName: "product/meetings",
        },
      ],
    },
  ],
  developerSidebar: [
    /// "projects/about",
    {
      type: "category",
      label: "afetharita",
      link: {type: "doc", id: "projects/afetharita.com/afetharita.com"},
      items: [
        {
          type: "autogenerated",
          dirName: "projects/afetharita.com",
          // docId: "project/afetharita.com/product/"
        },
      ],
    },
    {
      type: "category",
      label: "deprem.io",
      items: [
        {
          type: "autogenerated",
          dirName: "projects/deprem.io",
        },
      ],
    },
  ],
};

module.exports = sidebars;