/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  productSidebar: [
    "product/product",
    {
      type: "category",
      label: "Mission",
      items: [
        {
          type: "autogenerated",
          dirName: "product/mission",
        },
      ],
    },
    {
      type: "category",
      label: "Vision",
      items: [
        {
          type: "autogenerated",
          dirName: "product/vision",
        },
      ],
    },
    {
      type: "category",
      label: "Progress",
      items: [
        {
          type: "autogenerated",
          dirName: "product/progress",
        },
      ],
    },
    {
      type: "category",
      label: "Meetings",
      items: [
        {
          type: "autogenerated",
          dirName: "product/meetings",
        },
      ],
    },
  ],
  developerSidebar: [
    "developer/developer",
    {
      type: "category",
      label: "afetharita",
      items: [
        {
          type: "autogenerated",
          dirName: "developer/afetharita.com",
        },
      ],
    },
    {
      type: "category",
      label: "deprem.io",
      items: [
        {
          type: "autogenerated",
          dirName: "developer/deprem.io",
        },
      ],
    },
  ],
};

module.exports = sidebars;
